name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python test deps (no llama-cpp)
        working-directory: model_server
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt fastapi==0.111.0 uvicorn[standard]==0.30.1 pydantic==2.8.2

      - name: Python tests
        run: pytest -q model_server/tests
